deployment/production/docker.md

This adds instructions on what command to run to set up the database on a clean installation.

docs: add instructions on how to setup the database the first time

---

docs/product/channels/live-chat/sdk/identity-validation.md

Having the hash.digest('hex') on another line without an assignment seemed confusing.

Refined the Node.js Identity validation sample

---

docs/self-hosted/deployment/docker.md

What do you think about this shortening of the rails console?
Once you exit, you'd be placed back outside the container.
Coupling this with an alias, I find can make things a little more natural for me.
* Does not specify path to shell, assumes it's executable is in the `PATH`
* Uses default `docker-compose up` container name, using `basepath` of `pwd` as a prefix, with predictable suffix.
* Continues to use `bundle exec`, so users can work-out nearly any bundler installed utility.

One-liner the rails console

---

docs/self-hosted/deployment/linux-vm.md

Currently, the script is pulled from develop and the branch run is master. This could cause breakages if the ruby version on develop is different than the one on master

chore: Update Ubuntu installation instructions

---

docs/self-hosted/deployment/storage/supported-providers.md

Documentation shows config value for storage needs single quotes(' '). But that is not the case, it fails the build, docker build & docker compose command as well.
Current config in doc: 
`ACTIVE_STORAGE_SERVICE='amazon'`
is should be 
`ACTIVE_STORAGE_SERVICE=amazon`

remove unnecessary quotes in config options

---

docs/self-hosted/configuration/environment-variables.md

Current documentation says: 
`ACTIVE_STORAGE_SERVICE='local'`
but it fails the docker image build as right value is 
`ACTIVE_STORAGE_SERVICE=local`

remove unnecessary quotes in storage configuration

---

docs/self-hosted/deployment/storage/supported-providers.md

- quotes around s3_compatible was causing rails to not pickup `minio`
- `minio` was failing to start when STORAGE_FORCE_PATH_STYLE was not set to true.
ref: --> https://github.com/chatwoot/chatwoot/pull/1134

Update config for using minio as active storage

---

docs/self-hosted/configuration/environment-variables.md

Fixes [#3396](https://github.com/chatwoot/chatwoot/issues/3396)

Fixes: Mention the env variables SMTP_TLS and SMTP_SSL in docs (#3396)

---

docs/self-hosted/configuration/features/integrations/facebook-channel-setup.md
docs/self-hosted/configuration/features/integrations/instagram-channel-setup.md

#165 According to facebook's updated policy they have deprecated manage_page permission, so all the new apps will have to have permission for `pages_read_engagement` to read the connected Instagram account.
https://developers.facebook.com/docs/graph-api/changelog/version7.0/

Chore: Facebook's updated policy to page's insights

---

docs/self-hosted/configuration/environment-variables.md
docs/self-hosted/configuration/features/integrations/facebook-channel-setup.md

Description
----
Priority to GlobalConfig changes are reverted and for the time being env vars will take precedence if set. 
- chore: revert references to GlobalConfig
ref: https://github.com/chatwoot/chatwoot/pull/3702

chore: revert references to GlobalConfig

---

docs/product/others/webhook-events.md

The ID of Agents Specified in Webhook events example is specified as a String Type but actually it's of Type Int

Fixed Doc Error in Specifying Agent ID Data Type (WebHook-events)

---

docusaurus.config.js
package.json
yarn.lock

Adds the new breadcrumbs feature!

feat: breadcrumbs

---

docs/product/others/webhook-events.md

The top leve "A sample webhook payload" section incorrectly has "initiated_at" as a string. Whereas a real webhook is sending an object with a "timestamp" field under it.
Also used the same date example as the other examples on this page.

Updated "initiated_at" field's type

---

docs/self-hosted/configuration/features/integrations/slack-integration-setup.md
docs/self-hosted/deployment/linux-vm.md

- serve the Linux installation script from memorable domain
- https://get.chatwoot.app/linux/install.sh
Fixes https://github.com/chatwoot/product/issues/379

doc: update linux install script domain

---

docs/self-hosted/configuration/environment-variables.md

Documentation on direct upload enabling, which we introduced according to https://edgeguides.rubyonrails.org/active_storage_overview.html#direct-uploads

chore: Documentation on direct_upload_enabled env var

---

docs/product/channels/sms/twilio.md
docs/product/others/interactive-messages.md
docs/self-hosted/deployment/linux-vm.md

Reason: These appeared as dead links in the SEO audit.

Fixing examples in docs misrepresented as links

---

docs/self-hosted/deployment/linux-vm.md
docs/self-hosted/deployment/upgrade.md

Fix https://github.com/chatwoot/docs/issues/332
cwctl --upgrade have issues with versions less than 2.7. Add a note to use manual upgrade steps if upgrading from old versions of Chatwoot.

chore: add note for upgrades if version less than 2.7

---

docs/product/channels/api/send-messages.md

The API documentation URL for creating a new message points to an incorrect URL. Which is fixed in this PR. 
https://www.chatwoot.com/docs/product/channels/api/send-messages/

Update new message api documentation URL

---

docs/self-hosted/deployment/docker.md

`curl -I localhost:3000/api` instead of `localhost:3000` to avoid the 302 redirect status.

doc: update docker guide

---

docs/self-hosted/deployment/caprover.md

add section to mention cloud storage setup for  data persistence in caprover installations

doc: update caprover guide

---

docs/self-hosted/deployment/docker.md

- add note to maintain backward compatibility for older docker versions

chore: update docker guide

---

docs/contributing-guide/mobile-app/setup-guide.md

In the docs location for gradle.properties for the Android app setup is mentioned incorrectly.
This file needs to be created inside root android folder and not inside android/app folder

Update android app setup instructions

---

docs/self-hosted/deployment/storage/gcs-bucket.md
docs/self-hosted/deployment/storage/supported-providers.md

For GCS setup in Chatwoot, the `GCS_CREDENTIALS` environment variable needs to be wrapped in single quotes starting with version 2.17.

doc: update gcs-bucket.md

---

.github/workflows/broken-links-check.yml

Context
----
We are having missing/broken/404 links in the website/docs due to the nature of the internet.  😅 
Changelog
----
- Add a gh action which will run monthly to scan for broken links
- This will create issues for broken links

feat: add gh action to check for broken links in chatwoot website

---

docs/self-hosted/configuration/features/email-channel/conversation-continuity.md

Changes the MANDRILL_INGRESS_API_KEY env var to MAILGUN_INGRESS_SIGNING_KEY, which is the correct one according to https://github.com/chatwoot/chatwoot/blob/develop/.env.example#L95

Fix an incorrect env var in conversation-continuity.md

---

docs/user-guide/features/notifications.md

chore: Update notifications Docs

---

docs/self-hosted/configuration/features/integrations/slack-integration-setup.md

I was double-checking the list of bot token scopes and I thought it would be much, much easier to double-check my work if the list of token scopes were both alphabetized and turned into a proper unordered list, matching the presentation in Slack itself.
I also took the liberty of improving the fidelity of the capitalization elsewhere in the document.

chore: Alphabetize and list-ize bot token scopes, etc.

---

docs/self-hosted/deployment/linux-vm.md

- Cwctl targetting chatwoot v4 is having some issues on Ubuntu 22.04
- This PR updates the recommended OS for new installations to the latest  LTS 24.04

doc: update cwctl target to 24.04 LTS

---

docs/self-hosted/deployment/docker.md

The proxy_set_header Connection directive was defined twice, causing a conflict. Remove the duplicate. 
Fixes https://linear.app/chatwoot/issue/CW-3958/invalid-nginx-config

doc: fix nginx config in docker guide

---

docs/self-hosted/deployment/linux-vm.md

- update the Linux manual upgrade instructions to be compatible with the latest Chatwoot requirements

doc: update linux manual upgrade guide

---

self-hosted/supported-features.mdx

docs: Update file size limits and formats for messaging channels
