chatwoot/docs

deployment/production/clevercloud.md

- Add deployment instructions to deploy to Clever Cloud

chore: Add deployment instructions to deploy to Clever Cloud

---

development/project-setup/conversation-continuity.md

**What:** fix mailgun api key env variable
**Why:** Related to https://github.com/chatwoot/chatwoot/issues/1425#issue-745456567
**How:**
- Lint docs
- Fix mailgun env variable name

fix mailgun api key env variable

---

deployment/production/caprover.md
deployment/production/docker.md
deployment/production/linux-vm.md

updating installation documentations

Chore: Update docs on installation

---

development/project-setup/conversation-continuity.md
development/project-setup/email-channel-setup.md

Documentation to add email channe

chore: Documentation to add email channel

---

development/project-setup/twitter-setup.md

I was beating my head against the wall a little bit before I found https://github.com/chatwoot/chatwoot/issues/1040#issuecomment-658279418. This PR makes it more clear that a "development environment" (a rather poor name on the Twitter side of things 😄) is required.

make it more clear a twitter development environment is required

---

docs/self-hosted/deployment/requirements.md
sidebars.js

docs explaining chatwoot requirements

chore: Chatwoot Requirements

---

docusaurus.config.js
package.json

chore: Change the base URL to move assets to /docs

---

docusaurus.config.js

fix: Add og:image

---

docusaurus.config.js

feat: Add Algolia Search

---

docs/handbook/marketing/brand-guidelines.md
sidebars.js

- Move notion document to marketing page

chore: Add brand guidelines to the handbook

---

docs/handbook/engineering/release-process.md
sidebars.js

chore: Add release process document

---

docs/contributing-guide/api-documentation.md
docs/contributing-guide/tests/cypress.md
docs/self-hosted/monitoring/super-admin-sidekiq.md
sidebars.js
src/css/custom.css
static/_redirects

- Add superadmin console docs
- Add cypress test docs
- Add Swagger build details

chore: Migrate Github wiki to docs

---

docs/contributing-guide/code-of-conduct.md

Update Contributor Covenant to 2.0

chore: Update Contributor Covenant to 2.0

---

docs/self-hosted/deployment/docker.md

-  minor changes to docker installation guidelines

chore: update docker installation guidelines

---

docs/self-hosted/configuration/features/integrations/facebook-channel-setup.md

- update Facebook page instructions

chore: Update facebook docs

---

docs/contributing-guide/environment-setup/windows.md

fix: Update <img> src using require.default

---

docs/self-hosted/deployment/linux-vm.md

chore: Add a note for AWS EC2 deploys

---

docs/product/channels/live-chat/integrations/nextjs.md
sidebars.js

- Add docs on how to add Chatwoot to Next.js
Fixes https://github.com/chatwoot/chatwoot/issues/2292

chore: Add Next.js docs

---

docs/contributing-guide/mobile-app/setup-guide.md

- Update the instructions for Sentry.

chore: Update instructions to build the mobile app

---

docs/self-hosted/deployment/docker.md

Keep uniformity with other docker-compose files in Chatwoot repo.

chore: fix bash command

---

docs/self-hosted.md
docs/self-hosted/telemetry.md
sidebars.js

ref : https://github.com/chatwoot/chatwoot/pull/2631

chore: add telemetry docs

---

docs/self-hosted.md
docs/self-hosted/deployment/helm-charts.md
sidebars.js

- Copy the contents from helm repo

feat: Add documentation for helm-charts

---

docs/contributing-guide/mobile-app/setup-guide.md
docs/product.md
docs/product/mobile-app/android.md
docs/product/mobile-app/ios.md
sidebars.js

- Cleanup RN setup guide
- Add Android and iOS in product handbook

chore: Cleanup react native guide

---

docs/contributing-guide/project-setup.md

Context
----
Based on a couple of frequent queries over discord, it seems this part was not clear enough.

doc: add repo cloning step to local setup guide

---

src/theme/Seo/index.js

feat: Auto generate meta images

---

docs/product.md

Formatting fix to remove extra bullet point

Update product.md: Formatting fix to remove extra bullet point

---

docs/self-hosted/deployment/helm-charts.md

- Add youtube video to helm docs

chore: Add helm video to the docs

---

docs/contributing-guide/environment-setup/docker.md

Fixes #98 
- Fixed bash highlighting breaks issue in docker setup markdown.
- Removed $ sign from bash block.

Bash  block highlighting breaks issue fixed and removed $ sign

---

docs/product/channels/live-chat/sdk/setup.md

Update sdk documentation

---

docs/self-hosted/deployment/helm-charts.md

- update helm chart doc to match chatwoot/charts README

Update helm docs to match charts README

---

docs/self-hosted/deployment/caprover.md

fixes https://github.com/chatwoot/chatwoot/issues/3475

fix Caprover upgrade instructions

---

config/sidebar/product.js
docs/product.md
docs/user-guide/features/keyboard-shortcuts.md

Fixes #141 
**Screen recording**
https://user-images.githubusercontent.com/64252451/144225888-b692448e-de61-429a-bf35-fdddda09019a.mov

doc: Keyboard shortcuts

---

config/sidebar/selfhosted.js
docs/self-hosted.md
docs/self-hosted/deployment/digital-ocean.md
docs/self-hosted/deployment/gcp.md

fix selfhosted sidebar

---

docs/self-hosted/deployment/aws.md
docs/self-hosted/deployment/azure.md
docs/self-hosted/deployment/gcp.md

- update cloud provider docs to mention k8s

update cloud provider docs to mention k8s

---

docs/self-hosted/configuration/features/integrations/facebook-channel-setup.md

Refer: https://github.com/chatwoot/chatwoot/pull/3518

Fix: Update facebook app version

---

docs/self-hosted/deployment/helm-charts.md

- update chatwoot image version
https://github.com/chatwoot/charts/pull/44

Update helm docs

---

docs/contributing-guide/environment-setup/docker.md
docs/self-hosted/deployment/docker.md

- Update prerequiste `docker` and `docker-compose` versions
﻿
ref: https://github.com/chatwoot/chatwoot/issues/2845

doc: update minimum docker and docker-compose version

---

docs/user-guide/conversation-workflow.md

Explain various conversation statuses in chatwoot

chore: conversation statuses update

---

docs/self-hosted/configuration/environment-variables.md

- Update env var docs to user super admin panel to be used for variables migrated to GlobalConfig
Fixes https://github.com/chatwoot/chatwoot/issues/3674

Update env var docs to mention InstallationConfig

---

docs/self-hosted/configuration/environment-variables.md

- doc: update account signup env var section

doc: update account signup env var section

---

docs/contributing-guide/environment-setup/mac-os.md
docs/contributing-guide/environment-setup/ubuntu.md
docs/contributing-guide/environment-setup/windows.md

doc: update fix for 191 updating ruby versions in docs

---

docs/self-hosted/deployment/docker.md

- update docker prod instructions to mention the localhost binding
ref: https://github.com/chatwoot/chatwoot/pull/3354#issuecomment-966114584

chore: update docker prod instructions

---

docs/self-hosted/configuration/environment-variables.md

So it is difficult to configure ChatWoot

Forgot to name the file

---

docs/product/channels/live-chat/sdk/setup.md

This will add a crucial sentence about HMAC having the great effect of having persistent logs!

Persisting logs in docs

---

docusaurus.config.js
package.json
yarn.lock

Upgrades the documentation to beta 15 (latest version). 
I did have to move the google analytics to make it work with the new version.  - It should all work fine.

Upgrade to beta 15 (latest)

---

docs/user-guide/contacts.md
docs/user-guide/conversation-workflow.md

doc: Add note in conversation assignment

---

docs/product/channels/live-chat/sdk/setup.md

Note: This needs to be merged once https://github.com/chatwoot/chatwoot/pull/3998 are made live.

doc: Add `chatwoot:error` event

---

docs/self-hosted/configuration/environment-variables.md

chore: minor doc updates

---

docusaurus.config.js
src/css/custom.css

Adds the announcement bar to the top of the docs pages. 
I'm not sure if the colours work, but feel free to edit or suggest changes.

Add announcement bar

---

config/sidebar/handbook.js
docs/handbook/engineering/swagger-documentation.md

chore: Add docs on how to update swagger

---

docs/product/others/websocket-events.md

- Update content to make it more readable

chore: Update websocket documenation to include more details

---

docs/self-hosted/configuration/features/integrations/slack-integration-setup.md

doc: update slack bot event subscriptions

---

docs/self-hosted/deployment/docker.md

- Update docker documentation to mention CE edition images
Related to https://github.com/chatwoot/chatwoot/pull/4406

doc: update docker ce edition images

---

docs/self-hosted/configuration/environment-variables.md

- remove vapid keys
- reorder based on relevance

doc: update env var guide

---

config/sidebar/product.js
docs/product.md
docs/product/others/faq.md

Add documentation about support channels and promoting services
fixes: https://github.com/chatwoot/product/issues/399

chore: Community FAQs

---

docs/product/others/agent-bots.md

chore: add avatar to agent bot

---

docs/self-hosted/deployment/storage/gcs-bucket.md

ref: https://discord.com/channels/647412545203994635/650257251856285707/974347949087809646

chore: update GCS docs

---

docs/product/others/faq.md

chore: Custom Branding in Chatwoot

---

docs/handbook/marketing/guidelines-taking-product-screenshots-or-screencasts.md

- Add a guideline to use real-world examples.

chore: Update screenshot guidelines

---

docs/self-hosted/deployment/linux-vm.md

Add a reference to hardware requirements
ref: https://github.com/chatwoot/chatwoot/issues/4933

doc: Update linux vm guide

---

docs/self-hosted/deployment/helm-charts.md

- improve formatting and legibility

doc: update helm charts section

---

config/sidebar/selfhosted.js
docs/self-hosted.md
docs/self-hosted/deployment/chatwoot-ctl.md
docs/self-hosted/deployment/linux-vm.md

- doc: add cwctl in linux guide
Related PR: https://github.com/chatwoot/chatwoot/pull/4836

doc: add cwctl in linux guide

---

config/sidebar/product.js
docs/product/others/dashboard-apps.md

Gif will be updated a staging data instance.

Docs for dashboard apps

---

docs/self-hosted/deployment/caprover.md

- Update caprover nginx config update

doc: update caprover docs

---

docs/self-hosted/deployment/helm-charts.md

Update helm chart docs with horizontal pod autoscaling support
Ref: https://github.com/chatwoot/charts/pull/73

doc: update helm chart guide wth hpa support

---

docs/self-hosted/deployment/helm-charts.md

Update helm guide with instructions for 1.0.0 chart version
Related to https://github.com/chatwoot/charts/pull/67

doc: update helm with instructions for v1 upgrade

---

docs/self-hosted/faq.md

chore: Document fair use policy

---

config/sidebar/contributingGuide.js
docs/contributing-guide/chatwoot-apis.md
docs/contributing-guide/contributors.md

chore: Document API types

---

docs/self-hosted/deployment/heroku.md

add note describing the deployment issues with Heroku at the moment

doc: update heroku doc with warning

---

config/sidebar/contributingGuide.js
docs/contributing-guide.md
docs/contributing-guide/security-reports.md

- Adding security report guidelines

chore: security guidelines

---

docs/self-hosted/deployment/aws.md

-  udpate aws manual install guide

doc: udpate aws manual install guide

---

docs/handbook/engineering/pr-guidelines.md

- updating pull request guidelines

chore: update pull request guidelines

---

docs/product/channels/whatsapp/whatsapp-cloud.md

- update wording in whatsapp docs

chore: update whatsapp docs

---

docs/self-hosted/deployment/helm-charts.md

Postgres related values changed with the `1.0.0` release of Charts.

doc: update helm guide to reflect postgres var change

---

docs/product/others/dashboard-apps.md

Chore: Update dashboard apps docs with querying information

---

docs/self-hosted/deployment/helm-charts.md

ref: https://github.com/chatwoot/chatwoot/issues/5506

doc: update helm chart guide with https troubleshooting

---

docs/self-hosted/runbooks/migrate-chatwoot-database.md

Fixes https://github.com/chatwoot/docs/issues/266

doc: update chatwoot db migrate guide

---

docs/self-hosted/deployment/helm-charts.md

relates to https://github.com/chatwoot/charts/pull/79

doc: update helm charts guide with new values.yaml parameter

---

docs/product/channels/live-chat/create-website-channel.md

- fix: broken links in website channel doc

fix: broken links in website channel doc

---

docs/product/channels/live-chat/sdk/setup.md

- Guide to use browser language for widget

feat: Add docs for `useBrowserLanguage`under widget SDK

---

docs/self-hosted/deployment/aws.md

- improve formatting and legibility

doc: update aws manual install guide

---

docs/product/channels/live-chat/integrations/vue.md

- fix chatwoot vue module urls

docs: fix chatwoot vue url

---

docs/self-hosted/configuration/environment-variables.md

Relates to https://github.com/chatwoot/chatwoot/pull/5899
Relates to https://github.com/chatwoot/chatwoot/issues/3696

doc: add postfix setup guide

---

docs/self-hosted/deployment/heroku.md

- add a note on the Heroku guide regarding Heroku discontinuing free plans.
Related to https://github.com/chatwoot/chatwoot/pull/5349

doc: update heroku guide

---

docs/product/others/dashboard-apps.md

adding agent context in documentation

feat: including agent context

---

docs/self-hosted/deployment/helm-charts.md

Changelog
----
- chore: update chatwoot version in helm guide
Related PR --> https://github.com/chatwoot/charts/pull/92

chore: update chatwoot version in helm guide

---

docs/self-hosted/configuration/features/integrations/facebook-channel-setup.md

- doc update for facebook integration with chatwoot

doc: update facebook channel setup

---

docs/self-hosted/configuration/environment-variables.md
yarn.lock

Add docs for LogRocket and Google OAuth

feat: add docs for LogRocket and Google OAuth

---

docs/self-hosted/deployment/linux-vm.md

- update ruby version in linux manual upgrade steps

doc: update linux manual upgrade steps

---

docs/product/channels/live-chat/integrations/vue.md

https://github.com/productdevbookcom/chatwoot

fix: vue and nuxt

---

docs/self-hosted/deployment/heroku.md

ref: https://github.com/chatwoot/chatwoot/pull/6932

chore: update heroku guide to mention runtime-metadata feature

---

docs/contributing-guide/environment-setup/ubuntu.md

chore: Update node js version ubuntu.md

---

docs/self-hosted/deployment/requirements.md

chore: update Redis requirement

---

config/sidebar/selfhosted.js
docs/self-hosted.md
docs/self-hosted/deployment/caprover.md
docs/self-hosted/deployment/clevercloud.md
docs/self-hosted/deployment/cloudron.md
docs/self-hosted/deployment/restack.md

- add note to mention community contributed installation setups
- refactor the sidebar to mention community contributed
Fixes https://linear.app/chatwoot/issue/CW-2017/tag-the-installation-documentation-as-community

doc: refactor installation types into community and official

---

docs/contributing-guide/project-setup.md

- chore: refactor contributing guide to use `make` commands

chore: refactor contributing guide to use make commands

---

docs/contributing-guide/environment-setup/mac-os.md
docs/contributing-guide/environment-setup/windows.md
docs/self-hosted/deployment/linux-vm.md

Changelog
- Update ruby version across the documentation (manual upgrade+setup guides for linux/windows/mac)
- From `3.1.3` to `3.2.2`

doc: update ruby version across docs

---

docs/self-hosted/configuration/enable-ip-logging.md

- Remove unused env var `IP_LOOKUP_SERVICE`
- Add instructions to enable/disable  `ip_lookup` via super admin console UI
ref: https://github.com/chatwoot/chatwoot/pull/6658

doc: Update enable-ip-logging.md

---

config/sidebar/contributingGuide.js
docs/contributing-guide.md
docs/contributing-guide/environment-setup/make.md

- add doc for `make` usage for local dev workflow

doc: add guide for make commands

---

docs/contributing-guide/environment-setup/mac-os.md
docs/contributing-guide/environment-setup/ubuntu.md
docs/contributing-guide/environment-setup/windows.md
docs/self-hosted/deployment/requirements.md

- update docs to mention node16 requirement in contribution guide
- mac, linux, windows

doc: update node version in contribution guide

---

docs/product/channels/live-chat/sdk/setup.md

Adds instructions to setup `baseDomain` under widget settings

doc: Adds configuration docs for baseDomain in SDK settings

---

docs/contributing-guide/environment-setup/mac-os.md
docs/contributing-guide/environment-setup/ubuntu.md
docs/contributing-guide/environment-setup/windows.md
docs/self-hosted/deployment/requirements.md

- Update node version requirement to 20 across docs

chore: update node version to 20 in docs

---

docs/self-hosted/configuration/features/integrations/slack-integration-setup.md

Fixes https://linear.app/chatwoot/issue/CW-2630/update-the-slack-docs-to-include-the-bot-permission-changes

chore: Add slack permission and link unfurl changes 

---

docs/product/channels/whatsapp/whatsapp-cloud.md

- Updated Whatsapp documentation with debug steps

chore: Whatsapp documentation

---

docs/contributing-guide.md
docs/contributing-guide/environment-setup/mac-os.md

- fix broken links
- add rbenv as option for managing ruby

chore: fix broken links

---

docs/contributing-guide/environment-setup/mac-os.md

- fixed postgres macOS setup instruction

chore: updated mac-os environment setup for postgres

---

docs/product/channels/supported-features.md

- update supported features across channels

chore: update supported features

---

docs/self-hosted/deployment/aws-marketplace.md

- update aws marketplace guide to  include a link to `chatwoot` listing

doc: update aws-marketplace deployment guide

---

.gitignore
docs/product/channels/whatsapp/whatsapp-cloud.md

- Update WhatsApp documentation to reflect `Webhook Verify Token` changes

chore: Update Whatsapp documentation

---

docs/self-hosted/configuration/features/integrations/instagram-channel-setup.md

Added facebook business_management api in documentation.

chore: Update instagram-channel-setup documentation

---

docs/self-hosted/deployment/storage/s3-bucket.md

Remove duplicate config for aws s3 bucket

chore: Update direct upload S3 config

---

docs/contributing-guide/environment-setup/docker.md

- update instructions to use docker for development

chore: update docker development

---

docs/contributing-guide/security-reports.md

- transitioning from huntr.dev

chore: Update security-reports.md

---

docs/self-hosted/monitoring/rate-limiting.md

- Add info about environment variables

chore: Update rack attack config

---

docs/self-hosted/configuration/environment-variables.md

- add notes on how to generate SECRET_KEY_BASE

doc: improve SECRET_KEY_BASE env var guide

---

docs/self-hosted/deployment/linux-vm.md

Add the notes for 22.04, 24.04.
Fixes https://github.com/chatwoot/chatwoot/issues/9654

chore(docs): Update linux-vm.md

---

docs/contributing-guide.md

Made some updates to fix grammar, punctuation, and style.

Fix: fixes #10100 - update contributing-guide.md to fix grammar, punctuation, and style.

---

docs/contributing-guide/environment-setup/docker.md

chore: update docker commands in contributing guide

---

docs/self-hosted/faq.md

- add faq for onboarding issue

doc: add faq for fixing onboarding screen issue

---

config/sidebar/selfhosted.js
docs/self-hosted/runbooks/upgrade-to-chatwoot-v4.md

- add chatwoot v4 migration guide

doc: add chatwoot v4 migration guide

---

docs/contributing-guide/contributors.md

Update the URL to use contributors.chatwoot.com

chore: Update contributors.md

---

docs/self-hosted/runbooks/upgrade-to-chatwoot-v4.md

- add v4 migration guide for k8s installations

doc: add v4 migration guide for k8s installations

---

README.md
docs/contributing-guide/environment-setup/mac-os.md
docs/contributing-guide/environment-setup/make.md
docs/contributing-guide/environment-setup/ubuntu.md
docs/contributing-guide/environment-setup/windows.md
docs/contributing-guide/project-setup.md
docs/contributing-guide/tests/cypress.md
docs/self-hosted/deployment/clevercloud.md

doc: refactor docs to use pnpm
